apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  generation: 1
  labels:
    app: endpoint-server
  name: endpoint-server
  namespace: public
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: endpoint-server
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: endpoint-server
    spec:
      containers:
        - image: krisnova/endpoint-server:latest
          imagePullPolicy: Always
          name: endpoint-server
          ports:
            - containerPort: 1337
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: endpoint-server
  name: endpoint-server
  namespace: public
spec:
  externalTrafficPolicy: Cluster
  ports:
    - nodePort: 30010
      port: 1337
      protocol: TCP
      targetPort: 1337
  selector:
    app: endpoint-server
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
