apiVersion: v1
kind: Pod
metadata:
  labels:
  name: nova
  namespace: default
spec:
  containers:
    - command:
        - /bin/bash
      image: krisnova/kubectl
      imagePullPolicy: Always
      name: nova
      securityContext:
        privileged: true
      stdin: true
      stdinOnce: true
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      tty: true
      volumeMounts:
        - mountPath: /root/.kube/config
          name: kubeconfig
        - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
          name: default-token-rn99c
          readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  hostNetwork: true
  hostPID: true
  nodeName: kluster-022-krisnova-kubecon-eu-21-control-plane-fbpl7
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Never
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
    - key: CriticalAddonsOnly
      operator: Exists
    - effect: NoExecute
      operator: Exists
  volumes:
    - hostPath:
        path: /etc/kubernetes/admin.conf
        type: ""
      name: kubeconfig
    - name: default-token-rn99c
      secret:
        defaultMode: 420
        secretName: default-token-rn99c